In [1]:
conda install numpy

Solving environment: | 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/noarch::bleach==3.2.1=py_0
  - defaults/osx-64::pip==20.2.4=py38hecd8cb5_0
  - defaults/osx-64::zope.interface==5.1.2=py38haf1e3a3_0
  - defaults/osx-64::anaconda==2020.11=py38_0
  - defaults/osx-64::nose==1.3.7=py38_1004
  - defaults/osx-64::zope.event==4.5.0=py38_0
  - defaults/noarch::nbformat==5.0.8=py_0
  - defaults/noarch::jsonschema==3.2.0=py_2
  - defaults/noarch::nltk==3.5=py_0
  - defaults/noarch::isort==5.6.4=py_0
  - defaults/osx-64::cython==0.29.21=py38hb1e8313_0
  - defaults/noarch::backports.functools_lru_cache==1.6.1=py_0
  - defaults/noarch::pygments==2.7.2=pyhd3eb1b0_0
  - defaults/noarch::qtconsole==4.7.7=py_0
  - defaults/osx-64::pylint==2.6.0=py38_0
  - defaults/osx-64::astropy==4.0.2=py38haf1e3a3_0
  - defaults/noarch::seaborn==0.11.0=py_0
  - defaults/noarch::conda-repo-cli==1.0.4=pyhd3eb1b0_0
  - def

done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 23.1.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _anaconda_depends-2020.07  |           py38_0           6 KB
    anaconda-custom            |           py38_1          35 KB
    ca-certificates-2023.01.10 |       hecd8cb5_0         121 KB
    charset-normalizer-2.0.4   |     pyhd3eb1b0_0          35 KB
    libllvm9-9.0.1             |       h21ff451_1        15.4 MB
    openssl-1.1.1t             |       hca72f7f_0         3.3 MB
    requests-2.28.1            |   py38hecd8cb5_0          93 KB
    setuptools-65.6.3          |   py38hecd8cb5_0         1.1 MB
    snappy-1.1.8               |       hb1e8313_

In [2]:
import numpy as np

In [3]:
#numpy array

In [4]:
my_list = [10,20,30,40]

In [5]:
type(my_list)

list

In [6]:
np.array(my_list)

array([10, 20, 30, 40])

In [7]:
my_numpy_array = np.array(my_list)

In [8]:
type(my_numpy_array)

numpy.ndarray

In [9]:
my_numpy_array

array([10, 20, 30, 40])

In [10]:
my_numpy_array[0]

10

In [11]:
my_numpy_array[-1]

40

In [12]:
my_numpy_array[0] = 100

In [13]:
my_numpy_array

array([100,  20,  30,  40])

In [14]:
my_numpy_array.max()

100

In [15]:
my_numpy_array.min()

20

In [16]:
my_numpy_array.mean()

47.5

In [17]:
matrix_list = [[1,0,0],[0,1,0],[0,0,1],[0,0,0]]

In [18]:
type(matrix_list)

list

In [20]:
matrix_list[0][0]

1

In [22]:
numpy_matrix_list = np.array(matrix_list)

In [23]:
numpy_matrix_list

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [25]:
numpy_matrix_list[0][0]

1

In [27]:
numpy_matrix_list.shape

(4, 3)

In [28]:
#arange

In [29]:
range(0,10)

range(0, 10)

In [30]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
#linspace

In [39]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [40]:
#random

In [45]:
np.random.randint(1,10,3)

array([6, 9, 7])

In [46]:
np.random.randint(1,100)

51

In [47]:
np.random.randint(1,100,10)

array([72, 32, 74,  2, 11, 97, 86, 58,  3, 36])

In [48]:
#numpy arrays methods

In [49]:
my_numpy_list = np.arange(0,20)

In [50]:
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [51]:
my_numpy_list[4]

4

In [52]:
my_numpy_list[4:9]

array([4, 5, 6, 7, 8])

In [53]:
my_numpy_list[4:9:2]

array([4, 6, 8])

In [54]:
my_list = list(range(0,20))

In [55]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [56]:
my_list[4:9:2]

[4, 6, 8]

In [59]:
#my_list[4:9] = -10

In [60]:
my_numpy_list[4:9] = -10

In [61]:
my_numpy_list

array([  0,   1,   2,   3, -10, -10, -10, -10, -10,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [62]:
other_list = np.arange(0,15)

In [63]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [64]:
other_list[4:10]

array([4, 5, 6, 7, 8, 9])

In [65]:
slicing_list = other_list[4:10]

In [66]:
slicing_list

array([4, 5, 6, 7, 8, 9])

In [67]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [68]:
slicing_list[0]

4

In [69]:
slicing_list[:] = 100

In [70]:
slicing_list

array([100, 100, 100, 100, 100, 100])

In [71]:
other_list

array([  0,   1,   2,   3, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14])

In [72]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [73]:
slicing_my_list = my_list[4:9]

In [74]:
slicing_my_list

[4, 5, 6, 7, 8]

In [76]:
slicing_my_list[0] = -100

In [77]:
slicing_my_list[1] = -100

In [78]:
slicing_my_list

[-100, -100, 6, 7, 8]

In [79]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [80]:
numpy_list_3 = np.arange(0,20)

In [81]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [82]:
numpy_list_3_copy = numpy_list_3.copy()

In [83]:
numpy_list_3_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [84]:
slicing_3 = numpy_list_3_copy[4:9]

In [86]:
slicing_3[:] = -100

In [87]:
slicing_3

array([-100, -100, -100, -100, -100])

In [88]:
numpy_list_3_copy

array([   0,    1,    2,    3, -100, -100, -100, -100, -100,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [89]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [90]:
#numpy operations with numpy arrays

In [91]:
new_array = np.random.randint(1,150,25)

In [92]:
new_array

array([145,  95,   3,  10,  26,  49,  76, 147, 130,  47,  21,  89,  55,
        48, 121,  36,  17,  39,  49,  70,  30,  85,  82,  92, 122])

In [93]:
new_array > 50

array([ True,  True, False, False, False, False,  True,  True,  True,
       False, False,  True,  True, False,  True, False, False, False,
       False,  True, False,  True,  True,  True,  True])

In [94]:
result_array = new_array > 50

In [95]:
result_array

array([ True,  True, False, False, False, False,  True,  True,  True,
       False, False,  True,  True, False,  True, False, False, False,
       False,  True, False,  True,  True,  True,  True])

In [96]:
new_array

array([145,  95,   3,  10,  26,  49,  76, 147, 130,  47,  21,  89,  55,
        48, 121,  36,  17,  39,  49,  70,  30,  85,  82,  92, 122])

In [97]:
new_array[result_array]

array([145,  95,  76, 147, 130,  89,  55, 121,  70,  85,  82,  92, 122])

In [98]:
last_array = np.arange(0,30)

In [99]:
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [100]:
last_array + last_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [101]:
last_array * last_array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [102]:
last_array - last_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [103]:
last_array / last_array

<ipython-input-103-8669891fd9be>:1: RuntimeWarning: invalid value encountered in true_divide
  last_array / last_array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [104]:
last_array.max()

29

In [105]:
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [106]:
np.max(last_array)

29

In [107]:
np.mean(last_array)

14.5

In [108]:
np.sqrt(last_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])